app:
  database:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  payment:
    force-failure: ${PAYMENT_FORCE_FAILURE:false}
    simulated-delay-ms: ${PAYMENT_DELAY_MS:0}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${SERVER_PORT:8080}
