app:
  database:
    url: jdbc:postgresql://localhost:5432/coworking
    username: coworking
    password: coworking
    driver-class-name: org.postgresql.Driver
  jwt:
    secret: "coworking-dev-secret-key-must-be-long-enough-256bits"
    expiration-ms: 86400000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
