spring:
  application:
    name: coworking-reservas
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

app:
  jwt:
    secret: "coworking-jwt-secret-key-change-me-32chars-min"
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
